### ISSUE TITLE
Python code block highlighting and copy button not working

### ISSUE THREAD

**Issue by DerkNiessink** [NatuurkundePracticumAmsterdam/PySide6-compact-documentation#26]
I added the pymdownx `markdown_extensions`  for highlighting code and tried adding the copy button, but both do not appear for some reason. I also tested this with other mkdocs themes, but this did not work either.

**Comment by AnneliesVlaar** [comment]
@davidfokkema heb jij een idee waarom dit niet werkt?

**Comment by AnneliesVlaar** [comment]
@DerkNiessink kan je wat code laten zien van hoe je het probeert werkend te krijgen?

**Comment by DerkNiessink** [comment]
I added two `features` to the `theme` section of the `mkdocs.yml` file:

``` yaml
theme:
  features: 
    - content.code.copy
    - content.code.select
 ``` 
 
And also the following markdown extensions:
 
``` yaml
markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
 ```
 
 This is how the code blocks in the docstrings look like:
 
```
``` py
label = QLabel()
Label.setText("Hello World")
print(label.text()) ```
```
